### ISSUE TITLE
Is the package maintained?

### ISSUE THREAD

**Issue by ErlanBelekov** [edmundhung/remix-worker-template#11]
Also there doesn't seem to be many examples of Cloudflare Workers + Remix, pls link any other maintained solutions if possible.

**Comment by edmundhung** [comment]
Hi @ErlanBelekov, this is a template/remix stack for running remix on Cloudflare workers with a custom adapter that utilise module workers. It should work with latest version of Remix. Is there any specific problem you had?

**Comment by ErlanBelekov** [comment]
@edmundhung I didn't see any recent commits that's why I chose to not try it at first.
Can emotion + chakra UI be integrated in this template too?

**Comment by edmundhung** [comment]
This template is integrating with tailwindcss currently. But you are free to clone it and change its setup for your need. For the integration, I would suggest asking in emotion / chakra UI repository if they support remix on Coudflare Workers first as not many existing solutions support the Cloudflare runtime out of the box.
